language: python
dist: xenial
python: 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenblas-base
  - pip install git+https://github.com/JesusTorrado/getdist/\#egg=getdist --user
script: pytest tests/test_prior_external.py
