language: python
dist: trusty
python: 2.7
# (Pre)Installation
# Test matrix for different C & fortran compilers
matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gfortran-4.9
            - openmpi-bin
            - openmpi-common
            - libopenmpi-dev
            # numpy (and more)
            - libopenblas-base
            # Planck likelihood
            - liblapack3
            - liblapack-dev
      env:
        - MATRIX_EVAL="4.9"
    # - addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - gcc-5
    #         - gfortran-5
    #         - openmpi-bin
    #         - openmpi-common
    #         - libopenmpi-dev
    #         # numpy (and more)
    #         - libopenblas-base
    #         # Planck likelihood
    #         - liblapack3
    #         - liblapack-dev
    #   env:
    #     - MATRIX_EVAL="5"
    # - addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - gcc-6
    #         - gfortran-6
    #         - openmpi-bin
    #         - openmpi-common
    #         - libopenmpi-dev
    #         # numpy (and more)
    #         - libopenblas-base
    #         # Planck likelihood
    #         - liblapack3
    #         - liblapack-dev
    #   env:
    #      - MATRIX_EVAL="6"
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-"${MATRIX_EVAL}" 90
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-"${MATRIX_EVAL}" 90
  # getdist fork (it will be an automatic requisite in the future)
  - pip install git+https://github.com/JesusTorrado/getdist/\#egg=getdist
  # optional, but necessary for tests
  - pip install mpi4py pytest-xdist
# Tests!
script:
  # Check
  - gfortran --version
  - gcc --version
  # Installation
  - python tests/cosmo_install.py ../modules
  # Not cosmological tests
  - pytest tests/ -k "not cosmo" -m "not slow and not mpi" --modules="../modules"
  # Cosmological tests (--boxed = 1 process per test; otherwise lowl planck lik fails!)
  - pytest tests/ -k "cosmo" -m "not slow and not mpi" --modules="../modules" --boxed
# Deploying to PyPI
# only if it buids and if the commit has been tagged
deploy:
  provider: pypi
  user: JesusTorrado
  password:
    secure: cNKtcKc/2oK3h1oAysKRi5ctfQUxsmxJ1UYd4DobmmPFdEnG4Gk5+1AliFEK/oXxg4y4qskpVoeOfyrWUZk4sB2UWiQ9zSg2agX1VBUxIvHRx2WMKpbSDkg/44kv1NzTKWqZEotI8k5UtDvOwoGaoy6gFW977r8nerVhQTM4j929SXZISzPfauBqaVeeq5v50DXpe43zzjr5LkdHhOw1Wz7akdnGkLwI71m4BL2yuh6CibXQZzFU5bRwEIED1nePCp6FuytZ205gXra2nHP2Zw1c8mSwVNkfQFJ88J2f3eqqtpOVR1d0ue/VN2yuSIT8GT1Cfn3dS08ocWz3MiLgNYweiFrVu8GQ/c99WxcA+3NDT+F9pC+WZUPnZ9XNwszuXsvN3B7vQ8haR466mypwCgBy0iOvH3KllxgzuHrzSMP4sK70uMqlCn3tbliwpF2fP1pdaDBv+WvNLqCdL60zeINrrOjHOB5dn+YztsoNaN41xWrsuWXfuW33UzHEPI0xl1l2C5CZfDFWWNgZqbFyB56XV1ne3Usy/SOZNmnbDqHqPB0MrzUEJ2KjPMhdPHF9bWrqXxIGSReOvj6XVsdIa/GyO/L1clhlpBTT6iT38IO5HnnIuL16rChggSR55L4DPXYv658zVPy+J6mLqDEM3Dix4HgSWLJ39l8VXYmsgz0=
  on:
    tags: true
